const GENERAL_ERROR = 500;
const BAD_REQUEST = 400;
const RESOURCE_NOT_FOUND = 404;
const STATUS_OK_CREATED = 201;
const STATUS_OK = 200;

module.exports = {
  GENERAL_ERROR,
  RESOURCE_NOT_FOUND,
  BAD_REQUEST,
  STATUS_OK_CREATED,
  STATUS_OK,
};